#!/bin/bash
#
# Show Master percentage for Alsa or PulseAudio

# Show Master volume level from Alsa
alsa() {
  amixer get Master -M | grep -oE "[[:digit:]]*%"
}

# Show MAster volume level from PulseAudio
pulse() {
  pactl list sinks | sed -n -e '/State: RUNNING/,$p' | awk '/\tVolume/ {print $5}'
}

# Test PulseAudio if it exists and/or configured
test_pulse() {
  pactl > /dev/null 2>&1
  return $?
}

send_output() {
  test_pulse
  if [[ "$?" -eq "0" ]]; then
    pulse
  else
    alsa
  fi
}

send_output
